### ISSUE TITLE
Error with FileReader not supporting reset()

### ISSUE THREAD

**Issue by Kamulau** [LTR4L/ltr4l#265]
Following error when executing train

Exception in thread "main" java.lang.IllegalArgumentException: java.io.IOException: reset() not supported
	at org.ltr4l.trainers.AbstractTrainer$TrainerFactory.getTrainer(AbstractTrainer.java:158)
	at org.ltr4l.cli.Train.main(Train.java:69)
Caused by: java.io.IOException: reset() not supported
	at java.io.Reader.reset(Reader.java:249)
	at org.ltr4l.trainers.AbstractTrainer$TrainerFactory.getTrainer(AbstractTrainer.java:154)
	... 1 more

**Comment by Kamulau** [comment]
AbstractTrainer:

`     */
    public static AbstractTrainer getTrainer(QuerySet trainingSet, QuerySet validationSet, Reader reader, Config override) {
      String algorithm;
      ObjectMapper mapper = new ObjectMapper();
      mapper.disable(JsonParser.Feature.AUTO_CLOSE_SOURCE);
      try{
        Map model = mapper.readValue(reader, Map.class);
        algorithm = ((String)model.get("algorithm")).toLowerCase();
        reader.reset();
        return getTrainer(algorithm, trainingSet, validationSet, reader, override);
      }
      catch (IOException e){
        throw new IllegalArgumentException(e);
      }
    }`
